/**
 * Example / mock quota pools for local demos and screenshots.
 *
 * Never imported by migrations or production boot. `pnpm capacity:seed-examples`
 * is the only entry. Values are invented and labeled as such.
 */

export const EXAMPLE_CAPACITY_SOURCE_NOTE = "Example / mock — not a real Tyler subscription limit.";

export const EXAMPLE_CAPACITY_POOLS = [
  {
    provider: "cursor",
    product: "Cursor Pro",
    poolKey: "example_cursor_pro_coding",
    displayName: "Cursor Pro coding (example)",
    remaining: 70,
    remainingUnit: "percent" as const,
    estimateConfidence: "estimated" as const,
    resetType: "monthly" as const,
    resetAt: new Date("2026-10-01T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: null,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
  {
    provider: "xai",
    product: "Grok Bot",
    poolKey: "example_grok_bot_weekly",
    displayName: "Grok Bot weekly (example)",
    remaining: 80,
    remainingUnit: "percent" as const,
    estimateConfidence: "estimated" as const,
    resetType: "weekly" as const,
    resetAt: new Date("2026-09-08T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: null,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
  {
    provider: "anthropic",
    product: "Claude subscription",
    poolKey: "example_claude_subscription",
    displayName: "Claude subscription (example)",
    remaining: 55,
    remainingUnit: "percent" as const,
    estimateConfidence: "estimated" as const,
    resetType: "monthly" as const,
    resetAt: new Date("2026-10-01T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: null,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
  {
    provider: "openai",
    product: "ChatGPT subscription",
    poolKey: "example_chatgpt_subscription",
    displayName: "ChatGPT subscription (example)",
    remaining: 60,
    remainingUnit: "percent" as const,
    estimateConfidence: "estimated" as const,
    resetType: "monthly" as const,
    resetAt: new Date("2026-10-01T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: null,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
  {
    provider: "google",
    product: "Gemini subscription",
    poolKey: "example_gemini_subscription",
    displayName: "Gemini subscription (example)",
    remaining: 90,
    remainingUnit: "percent" as const,
    estimateConfidence: "estimated" as const,
    resetType: "monthly" as const,
    resetAt: new Date("2026-10-01T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: null,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
  {
    provider: "openai",
    product: "PAYG API",
    poolKey: "example_openai_payg_api",
    displayName: "PAYG API budget (example)",
    remaining: 25,
    remainingUnit: "usd" as const,
    estimateConfidence: "estimated" as const,
    resetType: "monthly" as const,
    resetAt: new Date("2026-10-01T07:00:00.000Z"),
    resetTimezone: "America/Phoenix",
    lastVerifiedAt: new Date("2026-09-04T20:00:00.000Z"),
    hardDollarLimit: 50,
    sourceNote: EXAMPLE_CAPACITY_SOURCE_NOTE,
  },
] as const;
